### ISSUE TITLE
build: bump cosmos-sdk to v0.45.x

### ISSUE THREAD

**Issue by dongsam** [cosmosquad-labs/squad#125]
## Tasks

- [x] bump go 1.17
- [x] bump cosmos sdk from v0.44.5 to forked rc v0.45.3
- [x] bump budget rc release https://github.com/tendermint/budget/pull/116
- [x] replace cosmos sdk to v1.1.0-sdk-0.45.3 https://github.com/cosmosquad-labs/cosmos-sdk/releases/tag/v1.1.0-sdk-0.45.3
- [x] replace budget official release v1.2.0 
- [x] bump go-ibc from v2.0.2 to v2.2.0 https://github.com/cosmos/ibc-go/compare/v2.0.2...v2.2.0 with forked ibc-go( blockedAddr) https://github.com/cosmosquad-labs/ibc-go/pull/1
- [ ] ~~bump squad app to v2~~ (It would be bumped before release) https://github.com/cosmosquad-labs/squad/issues/306

## Ref
- https://github.com/cosmos/gaia/blob/main/docs/roadmap/cosmos-hub-roadmap-2.0.md#v7-theta-upgrade-expected-q1-2022
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
