### ISSUE TITLE
Add test codes for liquidstaking

### ISSUE THREAD

**Issue by dongsam** [cosmosquad-labs/squad#132]
## Summary

https://github.com/cosmosquad-labs/squad/pull/129 has become too big and the missing test code would be added this issue.

## Tasks

- [ ] Integration Test assertion
- [x] genesis
- [x] InvariantCheck https://github.com/cosmosquad-labs/squad/pull/143
- [x] Rebalancing, Tombstoned https://github.com/cosmosquad-labs/squad/pull/143
- [x] WithdrawRewards https://github.com/cosmosquad-labs/squad/pull/135
- [ ] grpc_query
- [x] types

## References

-
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
