### ISSUE TITLE
refactor liquidstaking

### ISSUE THREAD

**Issue by dongsam** [cosmosquad-labs/squad#142]
## Tasks

https://github.com/cosmosquad-labs/squad/pull/143
- [x] refactor ActiveCondition ( Active, InActive )
- [x] refactor rebalancing
- [x] remove valMap for optimize
- [x] apply crumb to activeLiquidVal[0] rule
- [x] tombstone handling( added slashingKeeper on liquidstakingKeeper)
- [x] add Invariant checks
- [x] update spec
- [x] update rebalancing logics
- [x] Add edgecase logics on MinMaxGap
- [x] TallyLiquidGov with votingPower ( bumped sdk rc3 )

https://github.com/cosmosquad-labs/squad/pull/151
- [x] refactor: tidy unused functions, update comments
- [x] fix: apply error types for liquidstaking

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
