### ISSUE TITLE
Too many queued stakings can cause slow block production

### ISSUE THREAD

**Issue by hallazzang** [cosmosquad-labs/squad#274]
We can put ending timestamp inside store keys to mitigate this problem.
When queuing staking, the end time is set to current blocktime + `time.Duration(params.NextEpochDays)`, and queued staking will be processed at the end time, not when the epoch increases.

## Tasks
- [x] Fix QueuedStaking logics
- [x] Fix relevant test cases
- [x] Add migration.go, legacy code https://github.com/cosmosquad-labs/squad/pull/283
- [x] bump `ConsensusVersion` of farming to 2 from 1 https://github.com/cosmosquad-labs/squad/pull/283
- [x] Update Spec, docs, cli help
