### ISSUE TITLE
Add MintPoolAddress on mint params to separate inflation with tx fee

### ISSUE THREAD

**Issue by dongsam** [cosmosquad-labs/squad#314]
## Summary

Add `params.MintPoolAddress` on the mint module to customize and separate inflation with tx fee

## Proposal

`mint_pool_address` defines the address where inflation will be minted, The default is `FeeCollector` It's the same value that's currently hardcoded, but if it set `FeeCollector`, it could mix the minted inflation with the collected tx fee. Therefore, it is recommended to specify a separate address depending on the chain

## Tasks

- [x] add `params.MintPoolAddress`
- [x] update ConsensusVersion of mint module 1 -> 2
- [x] add v2 upgrade handler ( state, migration )
- [x] update docs ( spec, swagger )

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
